#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Music-Gestalt
version:      0.02
version_from: lib/Music/Gestalt.pm
installdirs:  site
requires:
    MIDI:                          0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
